---
- name: create users
  hosts: all
  become: true
  vars_files:
    - user_list.yml
  tasks:
    - name: create users
      group:
        name: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"

    - name: add user
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"
